version: '3'
services:
  vueapp:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/app
    environment:
      - GOOGLE_CLIENT_ID=12345qwerty
      - CONVOY_API=91lx5912clT
      - ADMIN_EMAIL=nascal3@gmail.com
    command: npm run build

  nginx:
    image: nginx
    ports:
      - 3000:80
    volumes:
      - ./dist:/usr/share/nginx/html




